-- Here are the commands to validate the tables
SELECT count(*) FROM departments;
SELECT count(*) FROM categories;
SELECT count(*) FROM products;
SELECT count(*) FROM orders;
SELECT count(*) FROM order_items;
SELECT count(*) FROM customers;

-- ### Exercise 1 - Customer order count

-- Get order count per customer for the month of 2014 January.

-- * Tables - `orders` and `customers`
-- * Data should be sorted in descending order by count and ascending order by customer id.
-- * Output should contain `customer_id`, `customer_fname`, `customer_lname` and `customer_order_count`.

Select count(o.*) as customer_order_count, c.customer_id, c.customer_fname, c.customer_lname
from customers as c
Join orders as o
On c.customer_id = o.order_customer_id
where CAST(order_date as date) between '01-01-2014' and '31-01-2014'
Group by c.customer_id
order by c.customer_id ASC, customer_order_count DESC;


-- ### Exercise 2 - Dormant Customers ---(not able to validate)

-- Get the customer details who have not placed any order for the month of 2014 January.
-- * Tables - `orders` and `customers`
-- * Output Columns - **All columns from customers as is**
-- * Data should be sorted in ascending order by `customer_id`
-- * Output should contain all the fields from `customers`
-- * Make sure to run below provided validation queries and validate the output.

SELECT count(DISTINCT order_customer_id)
FROM orders
WHERE to_char(order_date, 'yyyy-MM') = '2014-01';

SELECT count(*)
FROM customers;

Select count(DISTINCT o.order_customer_id), *
from customers as c
Join orders as o
On c.customer_id = o.order_customer_id
where CAST(order_date as date) Not between '01-01-2014' and '31-01-2014'
Group by c.customer_id, c.customer_fname, c.customer_lname, c.customer_email, c.customer_password,
         c.customer_street, c.customer_city, c.customer_state, c.customer_zipcode,o.order_id, o.order_date,
		 o.order_customer_id, o.order_status
order by c.customer_id ASC;
 
 ---------Solution-----------------------

 SELECT count(*)
 from customers as C
 Left outer join orders as o
 On o.order_customer_id = c.customer_id
 And to_char(order_date, 'yyyy-MM') = '2014-01'

---------using Not in nested query--------

Select c.*
from Customers as C
Where c.customer_id NOT IN (
	Select o.order_customer_id
	from orders as o
	where o.order_customer_id = c.customer_id 
	  AND to_char(order_date, 'yyyy-MM') = '2014-01'
)
Order by 1
Limit 10;

}

-----using Not exists-----------
Select c.*
from customers as C
Where NOT EXISTS (
	Select o.order_customer_id
	From orders as o
	Where o.order_customer_id = c.customer_id
	   AND to_char(order_date, 'yyyy-MM') = '2014-01'
)
order by 1;

-- Get the difference
-- Get the count using solution query, both the difference and this count should match

-- * Hint: You can use `NOT IN` or `NOT EXISTS` or `OUTER JOIN` to solve this problem.

-- ### Exercise 3 - Revenue Per Customer

-- Get the revenue generated by each customer for the month of 2014 January
-- * Tables - `orders`, `order_items` and `customers`
-- * Data should be sorted in descending order by revenue and then ascending order by `customer_id`
-- * Output should contain `customer_id`, `customer_fname`, `customer_lname`, `customer_revenue`.
-- * If there are no orders placed by customer, then the corresponding revenue for a given customer should be 0.
-- * Consider only `COMPLETE` and `CLOSED` orders

Select count(o.*) as customer_order_count, c.customer_id, c.customer_fname, c.customer_lname, sum(oi.order_item_subtotal) as customer_revenue 
from customers as c
Left outer Join orders as o
On c.customer_id = o.order_customer_id
left outer Join order_items as oi
On oi.order_item_order_id = o.order_id
where CAST(order_date as date) between '01-01-2014' and '31-01-2014' and o.order_status IN ('COMPLETE','CLOSED')
Group by c.customer_id, c.customer_id, c.customer_fname, c.customer_lname, oi.order_item_subtotal
order by c.customer_id ASC, order_item_subtotal DESC;

--13299---

----solution --------------


Select count(*) 
From (
   Select c.customer_id, 
          c.customer_fname, 
		  c.customer_lname, 
		  round(sum(oi.order_item_subtotal)::numeric,2) as customer_revenue 
from customers as c
   Left outer Join orders as o
       On c.customer_id = o.order_customer_id
	   and to_char(order_date, 'yyyy-mm') = '2014-01'
	   and o.order_status in ('COMPLETE','CLOSED')
    left outer Join order_items as oi
      On oi.order_item_order_id = o.order_id
  Group by 1,2,3
)
as q;



Select c.customer_id, 
          c.customer_fname, 
		  c.customer_lname, 
		  coalesce(round(sum(oi.order_item_subtotal)::numeric,2),0) as customer_revenue 
		  from customers as c
   Left outer Join orders as o
       On c.customer_id = o.order_customer_id
	   and to_char(order_date, 'yyyy-mm') = '2014-01'
	   and o.order_status in ('COMPLETE','CLOSED')
    left outer Join order_items as oi
      On oi.order_item_order_id = o.order_id
  Group by 1,2,3
  Order by 4 DESC, 1
  Limit 10;

  
-- ### Exercise 4 - Revenue Per Category

-- Get the revenue generated for each category for the month of 2014 January
-- * Tables - `orders`, `order_items`, `products` and `categories`
-- * Data should be sorted in ascending order by `category_id`.
-- * Output should contain all the fields from `categories` along with the revenue as `category_revenue`.
-- * Consider only `COMPLETE` and `CLOSED` orders
Select cat.category_id, cat.category_department_id, cat.category_name, round(sum(oi.order_item_subtotal)::numeric,2) as customer_revenue 
from categories as cat
Join products as pd
On cat.category_id = pd.product_category_id
Join order_items as oi
On oi.order_item_product_id = pd.product_id
Join orders as o
On o.order_id = oi.order_item_order_id
where CAST(o.order_date as date) between '01-01-2014' and '31-01-2014' and o.order_status IN ( 'COMPLETED' , 'CLOSED')
Group by 1,2,3
Order by 1;

--30---

-- ### Exercise 5 - Product Count Per Department

-- Get the count of products for each department.
-- * Tables - `departments`, `categories`, `products`
-- * Data should be sorted in ascending order by `department_id`
-- * Output should contain all the fields from `departments` and the product count as `product_count`

Select d.department_id, d.department_name, count(product_id) as product_count
from departments as d
Join categories as cat
On cat.category_department_id = d.department_id
Join products as pd
On pd.product_category_id = cat.category_id
group by d.department_id, d.department_name
Order by d.department_id;

--6---


